<?php
// index.php
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SkyFactions</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <header>
        <h1>SkyFactions</h1>
    </header>
    <main>
        <div class="image-container">
            <!-- Placeholder for the 1600x1080 image -->
            <img src="placeholder-image.jpg" alt="SkyFactions Image">
        </div>
        <div class="sections">
            <div class="section-box" id="raids">
                <img src="raids-icon.png alt="Raids Icon">
                <p>Raids</p>
            </div>
            <div class="section-box" id="factions">
                <img src="factions-icon.png" alt="Factions Icon">
                <p>Factions</p>
            </div>
            <div class="section-box" id="islands">
                <img src="islands-icon.png" alt="Islands Icon">
                <p>Islands</p>
            </div>
        </div>
    </main>
    <footer>
        <p>&copy;This website was generated by TerraByteDev.</p>
    </footer>
</body>
</html>