<?php
// index.php
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SkyFactions</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <header>
        <h1>SkyFactions</h1>
    </header>
    <main>
        <div class="image-container">
            <!-- Placeholder for the 1600x1080 image -->
            <img src="placeholder-image.jpg" alt="SkyFactions Image">
        </div>
        <div class="sections">
            <a href="raids.php" class="section-box">
                <img src="raids-icon.jpg" alt="Raids Icon">
                <p>Raids</p>
            </a>
            <a href="factions.php" class="section-box">
                <img src="factions-icon.jpg" alt="Factions Icon">
                <p>Factions</p>
            </a>
            <a href="islands.php" class="section-box">
                <img src="islands-icon.jpg" alt="Islands Icon">
                <p>Islands</p>
            </a>
        </div>
    </main>
    <footer>
        <p>&copy;This website was generated by TerraByteDev</p>
    </footer>
</body>
</html>
